/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_brucetoo_jnitest_CUtils */

#ifndef _Included_com_brucetoo_jnitest_CUtils
#define _Included_com_brucetoo_jnitest_CUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_brucetoo_jnitest_CUtils
 * Method:    getCString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_brucetoo_jnitest_CUtils_getCString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
